Diagnostics to actions.yml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -16,6 +16,15 @@ jobs:
             
         steps:
           - uses: actions/checkout@v2
+          - name: Run Diagnostics
+            run: |
+              echo "=== Current User ==="
+              whoami
+              echo "=== Working directory ==="
+              pwd
+              echo "===Available Tools ==="
+              command -v node || echo "Node missing"
+              command -v docker || echp "Docker missing"
           - name: Checkout submodules
             run: git submodule update --init --recursive
           - uses: webfactory/ssh-agent@v0.5.3
